name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u "${{ secrets.CR_USER }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.CR_USER }}/local-k8s-stack:${{ github.sha }} ./app

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ secrets.CR_USER }}/local-k8s-stack:${{ github.sha }}